# Finálna, opravená a funkčná konfigurácia pre Render.com

services:
  # Definícia našej hlavnej webovej služby
  - type: web
    name: evidencia-nakladov
    env: docker
    # Politika reštartu: reštartuje kontajner, ak zlyhá
    restartPolicy: on-failure

    # Príkaz, ktorý sa spustí pri builde.
    # Urobí náš skript spustiteľným a potom ho spustí, aby vytvoril DB.
    buildCommand: "chmod +x ./init_db.sh && ./init_db.sh"

    # Pripojenie perzistentného disku priamo k tejto službe
    disk:
      name: naklady-data
      mountPath: /app/data
      sizeGB: 1
