# Opravená a funkčná konfigurácia pre Render.com

services:
  # Definícia našej webovej služby
  - type: web
    name: evidencia-nakladov
    env: docker
    restartPolicy: unless-stopped

    # Príkaz, ktorý sa spustí na začiatku.
    # Urobí náš skript spustiteľným a potom ho spustí.
    initialDeployHook: |
      chmod +x ./init_db.sh
      ./init_db.sh

    # Pripojenie disku k tejto službe.
    # 'disk' (jednotné číslo) odkazuje na disk definovaný nižšie.
    disk:
      name: naklady-data
      mountPath: /app/data

# Samostatná, vrchná sekcia na definovanie perzistentných diskov.
disks:
  # Definícia samotného disku.
  - name: naklady-data
    sizeGB: 1
