# Finálna a funkčná konfigurácia pre Render.com

# 1. Najprv definujeme všetky potrebné disky
disks:
  - name: naklady-data # Meno nášho perzistentného disku
    sizeGB: 1          # Najmenšia možná veľkosť

# 2. Potom definujeme služby, ktoré budú disky používať
services:
  # Definícia našej webovej služby
  - type: web
    name: evidencia-nakladov
    env: docker

    # Príkaz, ktorý sa spustí pri builde.
    # Urobí náš skript spustiteľným a potom ho spustí, aby vytvoril DB.
    buildCommand: "chmod +x ./init_db.sh && ./init_db.sh"

    # Pripojenie disku k tejto službe.
    # Odkazujeme na disk 'naklady-data' definovaný vyššie.
    disk:
      name: naklady-data
      mountPath: /app/data